name: Build WASM PGlite files

permissions:
  pull-requests: write
  issues: write
  contents: read

on:
  workflow_call:

jobs:
  build:
    name: Build WASM Postgres
    runs-on: ubuntu-22.04
    env:
      BUILD_CONFIG_FILE: postgres-pglite/pglite/.buildconfig
      PGROOT: /tmp/pglite
      TOTAL_MEMORY: 128MB
      CMA_MB: 16
      DEBUG: false
      OBJDUMP: true
      contrib: contrib
      extra: extra
      EXTRA_EXT: vector

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Set build parameters
        run: |
          cat ${{ env.BUILD_CONFIG_FILE }} >> $GITHUB_ENV

      - name: Build postgres WASM via emsdk
        working-directory: ${{ github.workspace }}/postgres-pglite
        env: 
          PGSRC: ${{ github.workspace }}/postgres-pglite
          POSTGRES_PGLITE_OUT: ${{ github.workspace }}/packages/pglite/release
        run: |
          pglite/cibuild/build-with-docker.sh

      # - name: Upload Postgres to Github artifacts
      #   id: upload-postgres-wasm
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: postgres-wasm
      #     path: /tmp/sdk/postgres-*.tar.gz
      #     retention-days: 60

      - name: Upload PGlite Interim to Github artifacts
        id: upload-pglite-interim-build-files
        uses: actions/upload-artifact@v4
        with:
          name: pglite-interim-build-files
          path: ./packages/pglite/release/**
          retention-days: 60

      # - name: Upload PGlite Web Interim to Github artifacts
      #   id: upload-demos
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pglite-web-build-files
      #     path: /tmp/web/**
      #     retention-days: 60

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Built bundles

      - name: Create or update build outputs comment
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        continue-on-error: true
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Built bundles:
            - Interim build files: ${{ steps.upload-pglite-interim-build-files.outputs.artifact-url }}
          edit-mode: replace
