name: Test Docker on GitHub Actions

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Build as described in README.md'
  push:
    branches:
      - 'tudor/feat-docker-action'

jobs:
  readmemd_build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    container:
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io git wget

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Build all
        run: |
          pnpm install
          pnpm build:all